<?php

use smtech\CanvasPest\CanvasPest;
use Battis\BootstrapSmarty\NotificationMessage;

if (isset($_SESSION['toolProvider']->user)) {
	$_SESSION['canvasInstanceUrl'] = 'https://' . $_SESSION['toolProvider']->user->getResourceLink()->settings['custom_canvas_api_domain'];
} else {
	$_SESSION['canvasInstanceUrl'] = $metadata['CANVAS_INSTANCE_URL'];
}

if (isset($_SESSION['apiUrl']) && isset($_SESSION['apiToken'])) {
	$api = new CanvasPest($_SESSION['apiUrl'], $_SESSION['apiToken']);
} else {
	$api = new CanvasPest($metadata['CANVAS_API_URL'], $metadata['CANVAS_API_TOKEN']);
}

/* argument values for sync */
define('SCHEDULE_ONCE', 'once');
define('SCHEDULE_WEEKLY', 'weekly');
define('SCHEDULE_DAILY', 'daily');
define('SCHEDULE_HOURLY', 'hourly');
define('SCHEDULE_CUSTOM', 'custom');

define('LOCAL_TIMEZONE', 'US/Eastern'); // TODO: Can we detect the timezone for the Canvas instance and use it?
define('SEPARATOR', '_'); // used when concatenating information in the cache database
define('CANVAS_TIMESTAMP_FORMAT', 'Y-m-d\TH:iP');
define('SYNC_TIMESTAMP_FORMAT', 'Y-m-d\TH:iP'); // same as CANVAS_TIMESTAMP_FORMAT, FWIW

define('VALUE_OVERWRITE_CANVAS_CALENDAR', 'overwrite');
define('VALUE_ENABLE_REGEXP_FILTER', 'enable_filter');

/* cache database tables */

/* calendars
	id				hash of ICS and Canvas pairing, generated by getPairingHash()
	ics_url			URL of ICS feed
	canvas_url		canonical URL for Canvas object
	synced			sync identification, generated by getSyncTimestamp()
	modified		timestamp of last modificiation of the record
*/

/* events
	id					auto-incremented cache record id
	calendar			pair hash for cached calendar, generated by getPairingHash()
	calendar_event[id]	Canvas ID of calendar event
	event_hash			hash of cached event data from previous sync
	synced				sync identification, generated by getSyncTimestamp()
	modified			timestamp of last modification of the record
*/

/* schedules
	id			auto-incremented cache record id
	calendar	pair hash for cached calendar, generated by getPairingHash()
	crontab		crontab data for scheduled synchronization
	synced		sync identification, generated by getSyncTimestamp()
	modified	timestamp of last modification of the record
*/

$log = null;
function postMessage($subject, $body, $flag = NotificationMessage::INFO) {
	global $log;
	global $smarty;
	if (php_sapi_name() != 'cli') {
		$smarty->addMessage($subject, $body, $flag);
	} else {
		$logEntry = "[$flag] $subject: $body";
		if (is_a($log, Log::class)) {
			$log->log($logEntry);
		} else {
			echo "$logEntry\n";
		}
	}
}

/**
 * Generate a unique ID to identify this particular pairing of ICS feed and
 * Canvas calendar
 **/
function getPairingHash($icsUrl, $canvasContext) {
	global $metadata;
	return md5($icsUrl . $canvasContext . $metadata['CANVAS_INSTANCE_URL']);
}

$FIELD_MAP = array(
	'calendar_event[title]' => 'SUMMARY',
	'calendar_event[description]' => 'DESCRIPTION',
	'calendar_event[start_at]' => array (
		0 => 'X-CURRENT-DTSTART',
		1 => 'DTSTART'
	),
	'calendar_event[end_at]' => array(
		0 => 'X-CURRENT-DTEND',
		1 => 'DTEND'
	),
	'calendar_event[location_name]' => 'LOCATION'
);

/**
 * Generate a hash of this version of an event to cache in the database
 **/
function getEventHash($event) {
	global $FIELD_MAP;
	$blob = '';
	foreach ($FIELD_MAP as $field) {
		if (is_array($field)) {
			foreach ($field as $option) {
				if (!empty($property = $event->getProperty($option))) {
					$blob .= serialize($property);
					break;
				}
			}
		} else {
			if (!empty($property = $event->getProperty($field))) {
				$blob .= serialize($property);
			}
		}
	}
	return md5($blob);
}

/**
 * Generate a unique identifier for this synchronization pass
 **/
$SYNC_TIMESTAMP = null;
function getSyncTimestamp() {
	global $SYNC_TIMESTAMP;
	if ($SYNC_TIMESTAMP) {
		return $SYNC_TIMESTAMP;
	} else {
		$timestamp = new DateTime();
		$SYNC_TIMESTAMP = $timestamp->format(SYNC_TIMESTAMP_FORMAT) . SEPARATOR . md5((php_sapi_name() == 'cli' ? 'cli' : $_SERVER['REMOTE_ADDR']) . time());
		return $SYNC_TIMESTAMP;
	}
}

$_SESSION['canvasInstanceUrl'] = 'https://' . $_SESSION['toolProvider']->user->getResourceLink()->settings['custom_canvas_api_domain'];
$api = new CanvasPest($_SESSION['apiUrl'], $_SESSION['apiToken']);

?>
